stages:
  - build
  - deploy
build:
  stage: build
  tags:
    - Pages
deploy_production:
  stage: deploy
  tags:
    - Pages
  script:
    - echo "Deploying to server"
    - npm start
    - echo "Deployed"
  environment:
    name: dawgpackshowdown
    url: dawgpackshowdown.com
  only:
    - master